name: doker-build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: 'htolajide'
          password: 'olajide4me'
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          requirements: requirements.txt
          tags: htolajide/python-helloworld:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}